@extends('layouts.app')
@section('content')
<div class="min-h-screen bg-gray-300 ">
<div classs="min-h-screen min-w-full ppbackground">
      <div class="my_paper mx-2 relative bg-white px-20 pb-10">
          <p class="text-center font-bold font-serif text-4xl py-10">Privacy Policy of RedGEM.tech <span class="ml-7 text-red-500 text-sm">Updated at 2021-08-12</span></p>
           <br/>
          <h2 class="font-serif font-bold text-2xl mt-5">RedGEM (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by RedGEM.</h2>
          <br/>
          <p class="text-gray-500 font-sans text-xl">This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, RedGEM. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.</p>
          <h2 class="font-serif font-bold text-2xl mt-5">Definitions and key terms</h2>
          <p class="text-gray-500 font-sans text-xl mt-5">To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:</p>
          <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 "> -Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
            -Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to The RedGEM Technologies, Inc., (Mayfair) that is responsible for your information under this Privacy Policy.
             <br/>
            -Country: where RedGEM or the owners/founders of RedGEM are based, in this case is Nigeria
            <br/>
            -Customer: refers to the company, organization or person that signs up to use the RedGEM Service to manage the relationships with your consumers or service users.
            <br/>
            -Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit RedGEM and use the services.
            <br/>
            -IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
            <br/>
            -Personnel: refers to those individuals who are employed by RedGEM or are under contract to perform a service on behalf of one of the parties.
            <br/>
            -Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
            <br/>
            -Service: refers to the service provided by RedGEM as described in the relative terms (if available) and on this platform.
            <br/>
            -Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
            <br/>
            -Website: RedGEM."’s" site, which can be accessed via this URL: www.redgem.tech
            <br/>
            -You: a person or entity that is registered with RedGEM to use the Services.</p>
            <h2 class="font-serif font-bold text-2xl mt-5">What Information Do We Collect?</h2>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">
            We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
            </p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">
            -Name / Username
            -Phone Numbers
            -Email Addresses
            -Age
            -Password
            </p>
            <h2 class="font-serif font-bold text-2xl mt-5"> How Do We Use The Information We Collect?</h2>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">Any of the information we collect from you may be used in one of the following ways:</p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">-To personalize your experience (your information helps us to better respond to your individual needs)</p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">  -To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you</p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">
                -To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 "> -To process transactions</p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">-To administer a contest, promotion, survey or other site feature</p>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5 ">-To send periodic emails</p>

            <br/>
            <h2 class="font-serif font-bold text-2xl mt-5">When does RedGEM use customer information from third parties?</h2>
            <p class="text-gray-500 font-sans text-xl space-y-5 mt-5">
                We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a RedGEM customer, we receive information from a third party that provides automated fraud detection services to RedGEM. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.
            </p>


        </div>
</div>
</div>
@endsection
